export const UPDATE_CART_QUANTITY="UPDATE_CART_QUANTITY"
export const ADD_BOOKS_TO_CART="ADD_BOOKS_TO_CART"
export const REMOVE_BOOK_FROM_CART="REMOVE_BOOK_FROM_CART"
export const SET_BOOKS_IN_CART="SET_BOOKS_IN_CART"
